services:
  etl:
    build:
      context: .
    container_name: etl_py
    volumes:
      - ./src:/home/hadoop/src
      - ./tmp:/home/hadoop/tmp
      - ./logs:/home/hadoop/logs
      - ./data:/home/hadoop/data  
      - ./state:/home/hadoop/state
      - /etc/localtime:/etc/localtime:ro 
      - /etc/timezone:/etc/timezone:ro 
    working_dir: /home/hadoop/
    entrypoint: bash
    tty: true
    stdin_open: true
    networks:
      - hive_cluster_hnet
networks:
  hive_cluster_hnet:
    external: true
